package particle

const (
	randseed1 = 8979323846
)

// fastrand provides a faster way to generate a pseudo-random value.
// It expects a good seed (probably generated by a better RNG) plus
// the generator offset (the generation number sequence).
func fastrand(seed, i uint64) uint64 {
	x := seed + i
	x ^= x >> 12
	x ^= x << 25
	x ^= x >> 27
	return x * 2685821657736338717
}
